#!/bin/bash

# --------------------------------------------------------
#
# Check internet connections
#

printf "\nWired, Wireless, and VPN Status\n"
/usr/sbin/ip -br -c addr show

printf "\nBluetooth Status\n"
/usr/bin/hcitool dev
/usr/bin/hcitool con
printf "\n"

# --------------------------------------------------------
#
# TO DO
#

# - external ip addresses
# - dns servers
# - router info (name, addresses)
# - clean up ip addr field
